blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://github.com/datell1357/AI-Usage-for-Windows/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
